#!/usr/bin/env bash

bname=`basename $0`
usage="Usage: $bname count program"

if [ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null; then
    count=$1
else
    echo $usage
    exit
fi

if [ -n "$2" ]; then
    program=$2
else
    echo $usage
    exit
fi 

time (for i in `seq $count`; do $program; done) 2> .timetemp

cat .timetemp | awk -v count="$count" '/real/ { print ((substr($2,1,1)*60)/count)+(substr($2,3,5)/count)"s average ("count" calls)"}'

rm .timetemp
