#!/usr/bin/env bash

bname=`basename $0`
usage="Usage: $bname [count] program"
defaultcount=0

if [ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null; then
    count=$1
else
    count=10
    defaultcount=1
fi

if [ "$defaultcount" -eq 1 ]; then
    if [ -n "$1" ] && [ -x $1 ]; then
        program=$1
    else
        echo $usage
        exit
    fi
else
    if [ -n "$2" ] && [ -x "$2" ]; then
        program=$2
    else
        echo $usage
        exit
    fi
fi

time (for i in `seq $count`; do $program; done) 2> .timetemp

cat .timetemp | awk -v count="$count" '/real/ { print ((substr($2,1,1)*60)/count)+(substr($2,3,5)/count)"s average ("count" calls)"}'

rm .timetemp
